swagger: "2.0"
info:
  title: "Review Assistant"
  version: "1.0"
  description: "API for review assistant"
basePath: "/"
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /api/auth/get_token:
    post:
      tags:
        - Authentication
      summary: Get a token for a registered app
      parameters:
        - in: body
          name: credentials
          description: Name of the app, public key for the app, and name of the platform where the app is running
          required: true
          schema:
            type: object
            properties:
              app_name:
                type: string
                description: Name of the app
              public_key:
                type: string
                description: Public key for the app
              platform:
                type: string
                description: Name of the platform where the app is running
      responses:
        200:
          description: Token generated successfully
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: Access token for the app
              token_type:
                type: string
                description: Type of the access token
              expires_in:
                type: integer
                description: Number of seconds until the access token expires
        400:
          description: Invalid app credentials